# 1. 유니버스 (KRX 300, 20260430 기준)

In [ ]:
import pandas as pd
from pathlib import Path

krx300_path = Path("KRX300.xlsx")
kospi_path = Path("kospi_업종.xlsx")
kosdaq_path = Path("kosdaq_업종.xlsx")

krx300 = pd.read_excel(krx300_path, dtype={"종목코드": str})
kospi = pd.read_excel(kospi_path, dtype={"종목코드": str})
kosdaq = pd.read_excel(kosdaq_path, dtype={"종목코드": str})

krx300["종목코드"] = krx300["종목코드"].str.zfill(6)
kospi["종목코드"] = kospi["종목코드"].str.zfill(6)
kosdaq["종목코드"] = kosdaq["종목코드"].str.zfill(6)

krx300_base = krx300[["종목코드", "종목명"]].copy()

sector_info = pd.concat(
    [
        kospi[["종목코드", "시장구분", "업종명"]],
        kosdaq[["종목코드", "시장구분", "업종명"]],
    ],
    ignore_index=True,
).drop_duplicates(subset=["종목코드"], keep="first")

krx300_with_sector = krx300_base.merge(
    sector_info,
    on="종목코드",
    how="left",
)

output_path = "KRX300_업종.xlsx"
krx300_with_sector.to_excel(output_path, index=False)

print("저장 완료:", output_path)
display(krx300_with_sector.head())

저장 완료: /Users/b58230717/Desktop/MAGA/project/data/KRX300_업종.xlsx

/Users/b58230717/Desktop/MAGA/project/.venv/lib/python3.14/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Users/b58230717/Desktop/MAGA/project/.venv/lib/python3.14/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Users/b58230717/Desktop/MAGA/project/.venv/lib/python3.14/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

     종목코드       종목명   시장구분      업종명
0  005930      삼성전자  KOSPI    전기·전자
1  000660    SK하이닉스  KOSPI    전기·전자
2  402340     SK스퀘어  KOSPI     기타금융
3  005380       현대차  KOSPI  운송장비·부품
4  373220  LG에너지솔루션  KOSPI    전기·전자

In [32]:
import pandas as pd
from pathlib import Path

path = "KRX300_업종.xlsx"
df = pd.read_excel(path, dtype={"종목코드": str})

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297 entries, 0 to 296
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   종목코드    297 non-null    object
 1   종목명     297 non-null    object
 2   시장구분    297 non-null    object
 3   업종명     297 non-null    object
dtypes: object(4)
memory usage: 9.4+ KB

In [33]:
# 시장구분별 종목 수
market_counts = df["시장구분"].value_counts(dropna=False)
print("시장구분별 종목 수")
display(market_counts)

# 업종명 unique 개수와 목록
sector_names = (
    df["업종명"]
    .dropna()
    .astype(str)
    .str.strip()
    .sort_values()
    .unique()
)
print("unique 업종명 개수:", len(sector_names))
print("업종명 목록:")
for name in sector_names:
    print(name)

시장구분별 종목 수

시장구분
KOSPI     227
KOSDAQ     70
Name: count, dtype: int64

unique 업종명 개수: 23
업종명 목록:
IT 서비스
건설
금속
금융
기계·장비
기타금융
보험
비금속
섬유·의류
오락·문화
운송·창고
운송장비·부품
유통
은행
음식료·담배
의료·정밀기기
일반서비스
전기·가스
전기·전자
제약
증권
통신
화학

## 2. 한국투자증권 OPENAPI의 [국내주식]종목조회 - 주식기본조회를 이용하여 산업분류코드 및 업종분류코드 매핑

In [13]:
import os
from dotenv import load_dotenv

load_dotenv()

APP_KEY = os.getenv("KIS_APP_KEY")
APP_SECRET = os.getenv("KIS_APP_SECRET")
ACCOUNT_NO = os.getenv("KIS_ACCOUNT_NO")
ACCOUNT_CD = os.getenv("KIS_ACCOUNT_CD")
IS_PAPER = os.getenv("KIS_IS_PAPER", "true").lower() == "true"

BASE_URL = (
    "https://openapivts.koreainvestment.com:29443"
    if IS_PAPER
    else "https://openapi.koreainvestment.com:9443"
)

print("BASE_URL:", BASE_URL)
print("APP_KEY loaded:", APP_KEY is not None)
print("APP_SECRET loaded:", APP_SECRET is not None)
print("ACCOUNT loaded:", ACCOUNT_NO, ACCOUNT_CD)

BASE_URL: https://openapi.koreainvestment.com:9443
APP_KEY loaded: True
APP_SECRET loaded: True
ACCOUNT loaded: 44287740 01

In [14]:
import json
import requests

def get_access_token():
    url = f"{BASE_URL}/oauth2/tokenP"
    headers = {"content-type": "application/json"}
    body = {
        "grant_type": "client_credentials",
        "appkey": APP_KEY,
        "appsecret": APP_SECRET,
    }

    res = requests.post(url, headers=headers, data=json.dumps(body), timeout=10)
    print("status_code:", res.status_code)

    data = res.json()

    if "access_token" not in data:
        raise RuntimeError(f"토큰 발급 실패: {data}")

    return data

token_data = get_access_token()
ACCESS_TOKEN = token_data["access_token"]
token_data

status_code: 200

{'access_token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b2tlbiIsImF1ZCI6IjA4NTc1NWIwLTc4MWItNDk2ZC05NzcwLTgwZTY2YmU1NGRiOSIsInByZHRfY2QiOiIiLCJpc3MiOiJ1bm9ndyIsImV4cCI6MTc3NzY4NjQ0NywiaWF0IjoxNzc3NjAwMDQ3LCJqdGkiOiJQU1RKSER2a1owSmYyckRFcWlLV0xWRUhUcVoxYURtblFydE0ifQ.4r0jTzL7dn5DLUvKnJkocN-7594ZXSuVak3lqL_rJIMw6IElC7fRVXjQ8rdaCIco3pbiUOPJO8q6eMAGAigeug',
 'access_token_token_expired': '2026-05-02 10:47:27',
 'token_type': 'Bearer',
 'expires_in': 86400}

In [15]:
def get_websocket_approval_key():
    url = f"{BASE_URL}/oauth2/Approval"
    headers = {
        "content-type": "application/json; utf-8",
    }
    body = {
        "grant_type": "client_credentials",
        "appkey": APP_KEY,
        "secretkey": APP_SECRET,  # 문서 기준: secretkey == appsecret
    }

    res = requests.post(url, headers=headers, json=body, timeout=10)
    data = res.json()

    if "approval_key" not in data:
        raise RuntimeError(data)

    return data

approval_key = get_websocket_approval_key()
WEBSOCKET_KEY = approval_key["approval_key"]
approval_key

{'approval_key': '372d7de8-2d91-47e9-aff5-50f6483d5db9'}

In [34]:
import time
import requests
import pandas as pd
from pathlib import Path
from tqdm.auto import tqdm

input_path = "KRX300_업종.xlsx"
output_path = "KRX300_업종_KIS산업분류.xlsx"

df = pd.read_excel(input_path, dtype={"종목코드": str})
df["종목코드"] = df["종목코드"].str.zfill(6)

print("입력 파일:", input_path)
print("종목 수:", len(df))
display(df.head())

입력 파일: KRX300_업종.xlsx
종목 수: 297

     종목코드       종목명   시장구분      업종명
0  005930      삼성전자  KOSPI    전기·전자
1  000660    SK하이닉스  KOSPI    전기·전자
2  402340     SK스퀘어  KOSPI     기타금융
3  005380       현대차  KOSPI  운송장비·부품
4  373220  LG에너지솔루션  KOSPI    전기·전자

In [35]:
def get_kis_stock_info(stock_code: str) -> dict:
    url = f"{BASE_URL}/uapi/domestic-stock/v1/quotations/search-stock-info"

    headers = {
        "content-type": "application/json; charset=utf-8",
        "authorization": f"Bearer {ACCESS_TOKEN}",
        "appkey": APP_KEY,
        "appsecret": APP_SECRET,
        "tr_id": "CTPF1002R",
        "custtype": "P",
    }

    params = {
        "PDNO": stock_code,
        "PRDT_TYPE_CD": "300",
    }

    res = requests.get(url, headers=headers, params=params, timeout=10)
    res.raise_for_status()

    data = res.json()

    if data.get("rt_cd") != "0":
        raise RuntimeError(f"{stock_code} 조회 실패: {data.get('msg_cd')} / {data.get('msg1')}")

    return data.get("output", {})

In [36]:
# KIS 응답에서 가져올 산업/분류 관련 필드
target_fields = {
    "std_idst_clsf_cd": "표준산업분류코드",
    "std_idst_clsf_cd_name": "표준산업분류명",
    "idx_bztp_lcls_cd": "지수업종대분류코드",
    "idx_bztp_lcls_cd_name": "지수업종대분류명",
    "idx_bztp_mcls_cd": "지수업종중분류코드",
    "idx_bztp_mcls_cd_name": "지수업종중분류명",
    "idx_bztp_scls_cd": "지수업종소분류코드",
    "idx_bztp_scls_cd_name": "지수업종소분류명",
    "mket_id_cd": "시장ID코드",
    "excg_dvsn_cd": "거래소구분코드",
    "stck_kind_cd": "주식종류코드",
}

rows = []

for stock_code in tqdm(df["종목코드"], desc="KIS 종목정보 조회"):
    try:
        output = get_kis_stock_info(stock_code)

        row = {"종목코드": stock_code}
        for api_key, col_name in target_fields.items():
            row[col_name] = output.get(api_key, "")

        row["조회에러"] = ""

    except Exception as e:
        row = {"종목코드": stock_code}
        for col_name in target_fields.values():
            row[col_name] = ""
        row["조회에러"] = str(e)

    rows.append(row)

    # API 과호출 방지
    time.sleep(0.1)

kis_info = pd.DataFrame(rows)

display(kis_info.head())

KIS 종목정보 조회: 100%|██████████| 297/297 [01:12<00:00,  4.10it/s]

,종목코드,표준산업분류코드,표준산업분류명,지수업종대분류코드,지수업종대분류명,지수업종중분류코드,지수업종중분류명,지수업종소분류코드,지수업종소분류명,시장ID코드,거래소구분코드,주식종류코드,조회에러
0,005930,032604,통신 및 방송 장비 제조업,002,시가총액규모대,013,"전기,전자",013,"전기,전자",STK,02,101,
1,000660,032601,반도체 제조업,002,시가총액규모대,013,"전기,전자",013,"전기,전자",STK,02,101,
2,402340,116409,기타 금융업,,,,,,,STK,02,101,
3,005380,033001,자동차용 엔진 및 자동차 제조업,002,시가총액규모대,015,운수장비,015,운수장비,STK,02,101,
4,373220,032802,일차전지 및 축전지 제조업,,,,,,,STK,02,101,

In [37]:
# 기존 KRX300_업종 데이터에 KIS 산업분류 정보 붙이기
result = df.merge(
    kis_info,
    on="종목코드",
    how="left",
)

result.to_excel(output_path, index=False)

print("저장 완료:", output_path)
print("전체 행 수:", len(result))
print("조회 에러 수:", result["조회에러"].astype(str).str.strip().ne("").sum())

display(result.head())

저장 완료: KRX300_업종_KIS산업분류.xlsx
전체 행 수: 297
조회 에러 수: 0

,종목코드,종목명,시장구분,업종명,표준산업분류코드,표준산업분류명,지수업종대분류코드,지수업종대분류명,지수업종중분류코드,지수업종중분류명,지수업종소분류코드,지수업종소분류명,시장ID코드,거래소구분코드,주식종류코드,조회에러
0,005930,삼성전자,KOSPI,전기·전자,032604,통신 및 방송 장비 제조업,002,시가총액규모대,013,"전기,전자",013,"전기,전자",STK,02,101,
1,000660,SK하이닉스,KOSPI,전기·전자,032601,반도체 제조업,002,시가총액규모대,013,"전기,전자",013,"전기,전자",STK,02,101,
2,402340,SK스퀘어,KOSPI,기타금융,116409,기타 금융업,,,,,,,STK,02,101,
3,005380,현대차,KOSPI,운송장비·부품,033001,자동차용 엔진 및 자동차 제조업,002,시가총액규모대,015,운수장비,015,운수장비,STK,02,101,
4,373220,LG에너지솔루션,KOSPI,전기·전자,032802,일차전지 및 축전지 제조업,,,,,,,STK,02,101,

In [38]:
import pandas as pd
from pathlib import Path

path = "KRX300_업종_KIS산업분류.xlsx"
df = pd.read_excel(path, dtype={"종목코드": str})

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297 entries, 0 to 296
Data columns (total 16 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   종목코드       297 non-null    object
 1   종목명        297 non-null    object
 2   시장구분       297 non-null    object
 3   업종명        297 non-null    object
 4   표준산업분류코드   297 non-null    int64
 5   표준산업분류명    297 non-null    object
 6   지수업종대분류코드  203 non-null    float64
 7   지수업종대분류명   202 non-null    object
 8   지수업종중분류코드  184 non-null    float64
 9   지수업종중분류명   175 non-null    object
 10  지수업종소분류코드  185 non-null    float64
 11  지수업종소분류명   168 non-null    object
 12  시장ID코드     297 non-null    object
 13  거래소구분코드    297 non-null    int64
 14  주식종류코드     273 non-null    float64
 15  조회에러       0 non-null      float64
dtypes: float64(5), int64(2), object(9)
memory usage: 37.3+ KB

In [39]:
# 표준산업분류명별 개수
sector_counts = (
    df["업종명"]
    .dropna()
    .astype(str)
    .str.strip()
    .value_counts()
    .rename_axis("업종명")
    .reset_index(name="개수")
)

print("unique 업종명 개수:", len(sector_counts))
display(sector_counts)

unique 업종명 개수: 23

        업종명  개수
0     전기·전자  40
1      기타금융  35
2        화학  32
3     기계·장비  26
4        제약  25
5    IT 서비스  20
6     일반서비스  17
7        유통  17
8   운송장비·부품  13
9    음식료·담배  11
10       금속  10
11    오락·문화   9
12       증권   8
13       건설   7
14       보험   7
15    운송·창고   5
16  의료·정밀기기   3
17    전기·가스   3
18       통신   3
19       은행   2
20      비금속   2
21       금융   1
22    섬유·의류   1

In [40]:
# 표준산업분류명별 개수
sector_counts = (
    df["표준산업분류명"]
    .dropna()
    .astype(str)
    .str.strip()
    .value_counts()
    .rename_axis("표준산업분류명")
    .reset_index(name="개수")
)

print("unique 표준산업분류명 개수:", len(sector_counts))
display(sector_counts)

unique 표준산업분류명 개수: 76

             표준산업분류명  개수
0             기타 금융업  35
1      특수 목적용 기계 제조업  18
2           전자부품 제조업  14
3     소프트웨어 개발 및 공급업  13
4        기타 화학제품 제조업  13
..               ...  ..
71    그외 기타 운송장비 제조업   1
72               전기업   1
73      무기 및 총포탄 제조업   1
74            담배 제조업   1
75  동물성 및 식물성 유지 제조업   1

[76 rows x 2 columns]

In [42]:
import os
import json
import time
import pandas as pd
from dotenv import load_dotenv
from openai import OpenAI
from tqdm.auto import tqdm

load_dotenv()

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

NFR_sector = [
    "건설", "건자재", "광고", "금융", "기계", "휴대폰", "담배", "유통", "미디어", "바이오",
    "반도체", "보험", "석유화학", "섬유의류", "소프트웨어", "운수창고", "유틸리티", "은행",
    "인터넷포탈", "자동차", "전기전자", "제약", "조선", "종이", "증권", "철강금속", "타이어",
    "통신", "항공운송", "홈쇼핑", "음식료", "여행", "게임", "IT", "에너지", "해운",
    "지주회사", "디스플레이", "화장품", "자동차부품", "교육", "기타"
]

input_path = "KRX300_업종_KIS산업분류.xlsx"
output_path = "KRX300_업종_NFR업종.xlsx"

df = pd.read_excel(input_path, dtype={"종목코드": str})
df["종목코드"] = df["종목코드"].str.zfill(6)

display(df.head())

,종목코드,종목명,시장구분,업종명,표준산업분류코드,표준산업분류명,지수업종대분류코드,지수업종대분류명,지수업종중분류코드,지수업종중분류명,지수업종소분류코드,지수업종소분류명,시장ID코드,거래소구분코드,주식종류코드,조회에러
0,005930,삼성전자,KOSPI,전기·전자,32604,통신 및 방송 장비 제조업,2.0,시가총액규모대,13.0,"전기,전자",13.0,"전기,전자",STK,2,101.0,NaN
1,000660,SK하이닉스,KOSPI,전기·전자,32601,반도체 제조업,2.0,시가총액규모대,13.0,"전기,전자",13.0,"전기,전자",STK,2,101.0,NaN
2,402340,SK스퀘어,KOSPI,기타금융,116409,기타 금융업,NaN,NaN,NaN,NaN,NaN,NaN,STK,2,101.0,NaN
3,005380,현대차,KOSPI,운송장비·부품,33001,자동차용 엔진 및 자동차 제조업,2.0,시가총액규모대,15.0,운수장비,15.0,운수장비,STK,2,101.0,NaN
4,373220,LG에너지솔루션,KOSPI,전기·전자,32802,일차전지 및 축전지 제조업,NaN,NaN,NaN,NaN,NaN,NaN,STK,2,101.0,NaN

In [43]:
def normalize_text(value):
    if pd.isna(value):
        return ""
    return str(value).strip()


def classify_nfr_sector(row, model="gpt-4o-mini"):
    종목코드 = normalize_text(row.get("종목코드"))
    종목명 = normalize_text(row.get("종목명"))
    업종명 = normalize_text(row.get("업종명"))
    표준산업분류명 = normalize_text(row.get("표준산업분류명"))
    지수업종중분류명 = normalize_text(row.get("지수업종중분류명"))
    지수업종소분류명 = normalize_text(row.get("지수업종소분류명"))

    prompt = f"""
다음 종목의 업종 정보를 보고, 반드시 NFR_sector 중 하나만 선택하라.

판단 기준:
- 전체 정보를 종합해서 판단한다.
- 4개 업종 정보가 서로 다른 성격이면 `지수업종소분류명`을 가장 우선한다.
- 그다음 `지수업종중분류명`, `표준산업분류명`, `업종명` 순서로 참고한다.
- 종목명이 판단에 도움이 되면 보조적으로 참고한다.
- 애매하거나 맞는 분류가 없으면 "기타"를 선택한다.
- 출력은 지정된 JSON schema만 따른다.

[NFR_sector]
{NFR_sector}

[입력 정보]
종목코드: {종목코드}
종목명: {종목명}
업종명: {업종명}
표준산업분류명: {표준산업분류명}
지수업종중분류명: {지수업종중분류명}
지수업종소분류명: {지수업종소분류명}
"""

    response = client.responses.create(
        model=model,
        input=[
            {
                "role": "user",
                "content": prompt,
            }
        ],
        text={
            "format": {
                "type": "json_schema",
                "name": "nfr_sector_classification",
                "strict": True,
                "schema": {
                    "type": "object",
                    "properties": {
                        "sector": {
                            "type": "string",
                            "enum": NFR_sector,
                        }
                    },
                    "required": ["sector"],
                    "additionalProperties": False,
                },
            }
        },
    )

    result = json.loads(response.output_text)
    return result["sector"]

In [44]:
nfr_results = []
errors = []

for idx, row in tqdm(df.iterrows(), total=len(df), desc="NFR 업종 분류"):
    try:
        sector = classify_nfr_sector(row)
        error = ""
    except Exception as e:
        sector = "기타"
        error = str(e)

    nfr_results.append(sector)
    errors.append(error)

    time.sleep(0.1)

df["NFR업종"] = nfr_results
df["NFR업종_에러"] = errors

df.to_excel(output_path, index=False)

print("저장 완료:", output_path)
display(df.head())

NFR 업종 분류: 100%|██████████| 297/297 [06:51<00:00,  1.39s/it]

저장 완료: KRX300_업종_NFR업종.xlsx

,종목코드,종목명,시장구분,업종명,표준산업분류코드,표준산업분류명,지수업종대분류코드,지수업종대분류명,지수업종중분류코드,지수업종중분류명,지수업종소분류코드,지수업종소분류명,시장ID코드,거래소구분코드,주식종류코드,조회에러,NFR업종,NFR업종_에러
0,005930,삼성전자,KOSPI,전기·전자,32604,통신 및 방송 장비 제조업,2.0,시가총액규모대,13.0,"전기,전자",13.0,"전기,전자",STK,2,101.0,NaN,전기전자,
1,000660,SK하이닉스,KOSPI,전기·전자,32601,반도체 제조업,2.0,시가총액규모대,13.0,"전기,전자",13.0,"전기,전자",STK,2,101.0,NaN,반도체,
2,402340,SK스퀘어,KOSPI,기타금융,116409,기타 금융업,NaN,NaN,NaN,NaN,NaN,NaN,STK,2,101.0,NaN,금융,
3,005380,현대차,KOSPI,운송장비·부품,33001,자동차용 엔진 및 자동차 제조업,2.0,시가총액규모대,15.0,운수장비,15.0,운수장비,STK,2,101.0,NaN,자동차,
4,373220,LG에너지솔루션,KOSPI,전기·전자,32802,일차전지 및 축전지 제조업,NaN,NaN,NaN,NaN,NaN,NaN,STK,2,101.0,NaN,전기전자,

In [45]:
nfr_counts = (
    df["NFR업종"]
    .value_counts()
    .rename_axis("NFR업종")
    .reset_index(name="종목수")
)

display(nfr_counts)

    NFR업종  종목수
0      기타   51
1    전기전자   31
2      제약   23
3      기계   23
4    석유화학   18
5      금융   17
6      IT   17
7      유통   16
8      건설   11
9     반도체   11
10    음식료   10
11     증권    8
12     보험    7
13   철강금속    7
14  자동차부품    5
15   운수창고    5
16    바이오    4
17    화장품    4
18     게임    3
19     통신    3
20     조선    3
21    자동차    3
22     은행    2
23    타이어    2
24   유틸리티    2
25     여행    2
26    미디어    2
27   항공운송    1
28     담배    1
29  디스플레이    1
30   섬유의류    1
31     광고    1
32   지주회사    1
33  소프트웨어    1

### 딱히 매치가 잘안되는듯... 에코프로가 기타 금융업인게 기분나쁘지만 일단은 KRX의 2026년 4월 30일 기준 KRX300에 있는 종목데이터 + kospi/kosdaq 종목 업종데이터를 이용하여 KRX300.xlsx를 만들어 분석에 활용하자.

# 2. NFR 종목분석리포트

In [23]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse, parse_qs

BASE_URL = "https://finance.naver.com"
LIST_URL = "https://finance.naver.com/research/company_list.naver"

headers = {
    "User-Agent": "Mozilla/5.0",
    "Referer": "https://finance.naver.com/research/company_list.naver",
}

target_date = "2026-04-30"

page = 1

params = {
    "keyword": "",
    "brokerCode": "",
    "searchType": "writeDate",
    "writeFromDate": target_date,
    "writeToDate": target_date,
    "itemName": "",
    "itemCode": "",
    "x": 0,
    "y": 0,
    "page": page,
}

res = requests.get(
    LIST_URL,
    params=params,
    headers=headers,
    timeout=10,
)

res.raise_for_status()
res.encoding = "euc-kr"

soup = BeautifulSoup(res.text, "html.parser")

print("요청 URL:")
print(res.url)
print("상태 코드:", res.status_code)

요청 URL:
https://finance.naver.com/research/company_list.naver?keyword=&brokerCode=&searchType=writeDate&writeFromDate=2026-04-30&writeToDate=2026-04-30&itemName=&itemCode=&x=0&y=0&page=1
상태 코드: 200

In [30]:
report_elements = soup.select('a[href*="company_read.naver"]')

print("1페이지 리포트 수:", len(report_elements))

1페이지 리포트 수: 30

In [28]:
# 첫페이지에서 해당날짜의 총페이지수를 확인
last_page_element = None

for a in soup.select("a[href]"):
    text = a.get_text(" ", strip=True)
    
    if "맨뒤" in text:
        last_page_element = a
        break

print(last_page_element)

if last_page_element is not None:
    href = last_page_element.get("href")
    
    parsed = urlparse(href)
    query = parse_qs(parsed.query)
    
    last_page = int(query["page"][0])
else:
    # 리포트가 적어서 페이지가 1페이지만 있는 경우
    last_page = 1

print("총페이지 수:", last_page)

<a href="/research/company_list.naver?keyword=&amp;brokerCode=&amp;searchType=writeDate&amp;writeFromDate=2026-04-30&amp;writeToDate=2026-04-30&amp;itemName=&amp;itemCode=&amp;x=0&amp;y=0&amp;page=4">맨뒤
				<img alt="" border="0" height="5" src="https://ssl.pstatic.net/static/n/cmn/bu_pgarRR.gif" width="8"/>
</a>
총페이지 수: 4

In [ ]:
# 1페이지부터 마지막 페이지까지 리포트 수 확인하기
total_reports = 0

for page in range(1, last_page + 1):
    params = {
        "keyword": "",
        "brokerCode": "",
        "searchType": "writeDate",
        "writeFromDate": target_date,
        "writeToDate": target_date,
        "itemName": "",
        "itemCode": "",
        "x": 0,
        "y": 0,
        "page": page,
    }

    res = requests.get(
        LIST_URL,
        params=params,
        headers=headers,
        timeout=10,
    )

    res.raise_for_status()
    res.encoding = "euc-kr"

    page_soup = BeautifulSoup(res.text, "html.parser")

    page_report_elements = page_soup.select('a[href*="company_read.naver"]')
    page_report_count = len(page_report_elements)

    total_reports += page_report_count

    print(f"{page}페이지 리포트 수: {page_report_count}")
    print(res.url)
    print("-" * 80)

print("총페이지 수:", last_page)
print("총리포트 수:", total_reports)

1페이지 리포트 수: 30
https://finance.naver.com/research/company_list.naver?keyword=&brokerCode=&searchType=writeDate&writeFromDate=2026-04-30&writeToDate=2026-04-30&itemName=&itemCode=&x=0&y=0&page=1
--------------------------------------------------------------------------------
2페이지 리포트 수: 30
https://finance.naver.com/research/company_list.naver?keyword=&brokerCode=&searchType=writeDate&writeFromDate=2026-04-30&writeToDate=2026-04-30&itemName=&itemCode=&x=0&y=0&page=2
--------------------------------------------------------------------------------
3페이지 리포트 수: 30
https://finance.naver.com/research/company_list.naver?keyword=&brokerCode=&searchType=writeDate&writeFromDate=2026-04-30&writeToDate=2026-04-30&itemName=&itemCode=&x=0&y=0&page=3
--------------------------------------------------------------------------------
4페이지 리포트 수: 25
https://finance.naver.com/research/company_list.naver?keyword=&brokerCode=&searchType=writeDate&writeFromDate=2026-04-30&writeToDate=2026-04-30&itemName=&itemCode=&x=0&y=0&page=4
--------------------------------------------------------------------------------
총페이지 수: 4
총리포트 수: 115

In [33]:
first_report_element = report_elements[0]

first_report_title = first_report_element.get_text(" ", strip=True)
first_report_href = first_report_element.get("href")

# 핵심 수정 부분
first_report_url = urljoin("https://finance.naver.com/research/", first_report_href)

print("첫 번째 리포트 제목:", first_report_title)
print("첫 번째 리포트 href:", first_report_href)
print("첫 번째 리포트 URL:", first_report_url)

첫 번째 리포트 제목: 대외 사업 성장으로 호실적
첫 번째 리포트 href: company_read.naver?nid=92285&page=1&searchType=writeDate&writeFromDate=2026-04-30&writeToDate=2026-04-30
첫 번째 리포트 URL: https://finance.naver.com/research/company_read.naver?nid=92285&page=1&searchType=writeDate&writeFromDate=2026-04-30&writeToDate=2026-04-30

In [35]:
detail_res = requests.get(
    first_report_url,
    headers=headers,
    timeout=10,
)

detail_res.raise_for_status()
detail_res.encoding = "euc-kr"

detail_soup = BeautifulSoup(detail_res.text, "html.parser")

print("상세 페이지 URL:")
print(detail_res.url)
print("상태 코드:", detail_res.status_code)

target_table = detail_soup.select_one('table.type_1[summary="종목분석 리포트 본문내용"]')

print(target_table is not None)

상세 페이지 URL:
https://finance.naver.com/research/company_read.naver?nid=92285&page=1&searchType=writeDate&writeFromDate=2026-04-30&writeToDate=2026-04-30
상태 코드: 200
True

In [36]:
from pathlib import Path
import re
import pandas as pd

save_dir = Path("naver_company_reports") / target_date
save_dir.mkdir(parents=True, exist_ok=True)

save_dir

PosixPath('naver_company_reports/2026-04-30')

In [38]:
subject_element = target_table.select_one("th.view_sbj")

company_name = None
report_title = None
broker = None
report_date = None
views = None

# 종목명
company_tag = subject_element.select_one("span em")
if company_tag is not None:
    company_name = company_tag.get_text(strip=True)

# 증권사 | 날짜 | 조회수
source_tag = subject_element.select_one("p.source")
if source_tag is not None:
    source_text = source_tag.get_text("|", strip=True)
    source_parts = [x.strip() for x in source_text.split("|") if x.strip()]
    
    print("source_parts:", source_parts)
    
    if len(source_parts) >= 1:
        broker = source_parts[0]
    
    if len(source_parts) >= 2:
        report_date = source_parts[1]
    
    if len(source_parts) >= 3:
        views_text = source_parts[2]
        views_num = re.sub(r"[^0-9]", "", views_text)
        views = int(views_num) if views_num else None

# 리포트 제목
# subject_element 안에서 종목명 span, source p를 제거한 뒤 남은 텍스트를 제목으로 사용
subject_copy = BeautifulSoup(str(subject_element), "html.parser")
subject_copy_element = subject_copy.select_one("th.view_sbj")

for tag in subject_copy_element.select("span, p.source"):
    tag.decompose()

report_title = subject_copy_element.get_text(" ", strip=True)

print("종목명:", company_name)
print("리포트 제목:", report_title)
print("증권사:", broker)
print("작성일:", report_date)
print("조회수:", views)

source_parts: ['한화투자증권', '2026.04.30', '조회 6741']
종목명: LG씨엔에스
리포트 제목: 대외 사업 성장으로 호실적
증권사: 한화투자증권
작성일: 2026.04.30
조회수: 6741

In [39]:
target_price = None
investment_opinion = None

target_price_tag = target_table.select_one("em.money strong")
if target_price_tag is not None:
    target_price_text = target_price_tag.get_text(strip=True)
    target_price_num = re.sub(r"[^0-9]", "", target_price_text)
    target_price = int(target_price_num) if target_price_num else None

opinion_tag = target_table.select_one("em.coment")
if opinion_tag is not None:
    investment_opinion = opinion_tag.get_text(strip=True)

print("목표가:", target_price)
print("투자의견:", investment_opinion)

목표가: 90000
투자의견: Buy

In [41]:
body_element = target_table.select_one("td.view_cnt")
body_text = None
body_html = None

body_div = body_element.find("div") if body_element is not None else None

if body_div is not None:
    body_text = body_div.get_text("\n", strip=True)
    body_html = str(body_div)

print(body_text)

1Q26 실적은 컨센서스 부합
동사의 1Q26 실적은 매출액 1.32조 원, 영업이익 942억 원을 기록하며 시장 기대치에 부합했다. 비수기 및 매크로 환경 불확실 영향에도 불구 전사업 부문이 모두 호조세를 나타내며 매출액과 영업이익이 YoY 각각 8.6%, 19.4% 증가했다. DBS 매출은 YoY 11.9%나 성장했다. 기존 수주 대형 사업들의 안정적인 이행과 더불어 대외 고객들의 협업 기반이 확대되고 있는 것으로 파악된다. 클라우드&AI 매출은 대내외 AX 프로젝트 및 클라우드 인프라 수주를 통해 YoY 6.7% 성장했다. AI 인프라 및 MSP 사업의 지속적인 확대가 수익성 개선 핵심동력으로 작용하며 영업이익률은 YoY 0.7%p 상승한 7.2%를 기록했다.

In [43]:
pdf_elements = target_table.select('a[href*=".pdf"]')
pdf_urls = []

for a in pdf_elements:
    href = a.get("href")
    
    if href is None:
        continue
    
    if href not in pdf_urls:
        pdf_urls.append(href)

print(pdf_urls)

pdf_url = pdf_urls[0] if pdf_urls else None

print("선택된 PDF URL:", pdf_url)

['https://stock.pstatic.net/stock-research/company/16/20260430_company_410118000.pdf']
선택된 PDF URL: https://stock.pstatic.net/stock-research/company/16/20260430_company_410118000.pdf

In [45]:
def clean_filename(text):
    text = str(text)
    text = re.sub(r'[\\/:*?"<>|]', "_", text)
    text = text.strip()
    return text

safe_company = clean_filename(company_name)
safe_broker = clean_filename(broker)

pdf_filename = f"{report_date}_{safe_company}_{safe_broker}.pdf"

pdf_path = save_dir / pdf_filename

print(pdf_path)

naver_company_reports/2026-04-30/2026.04.30_LG씨엔에스_한화투자증권.pdf

In [46]:
pdf_headers = {
    "User-Agent": "Mozilla/5.0",
    "Referer": first_report_url,
}

pdf_res = requests.get(
    pdf_url,
    headers=pdf_headers,
    timeout=30,
)

pdf_res.raise_for_status()

with open(pdf_path, "wb") as f:
    f.write(pdf_res.content)

print("PDF 저장 완료:")
print(pdf_path)
print("파일 크기:", pdf_path.stat().st_size, "bytes")

PDF 저장 완료:
naver_company_reports/2026-04-30/2026.04.30_LG씨엔에스_한화투자증권.pdf
파일 크기: 670943 bytes

In [47]:
report_data = {
    "target_date": target_date,
    "company_name": company_name,
    "report_title": report_title,
    "broker": broker,
    "report_date": report_date,
    "views": views,
    "target_price": target_price,
    "investment_opinion": investment_opinion,
    "body_text": body_text,
    "pdf_url": pdf_url,
    "pdf_path": str(pdf_path),
    "detail_url": first_report_url,
}

report_data

{'target_date': '2026-04-30',
 'company_name': 'LG씨엔에스',
 'report_title': '대외 사업 성장으로 호실적',
 'broker': '한화투자증권',
 'report_date': '2026.04.30',
 'views': 6741,
 'target_price': 90000,
 'investment_opinion': 'Buy',
 'body_text': '1Q26 실적은 컨센서스 부합\n동사의 1Q26 실적은 매출액 1.32조 원, 영업이익 942억 원을 기록하며 시장 기대치에 부합했다. 비수기 및 매크로 환경 불확실 영향에도 불구 전사업 부문이 모두 호조세를 나타내며 매출액과 영업이익이 YoY 각각 8.6%, 19.4% 증가했다. DBS 매출은 YoY 11.9%나 성장했다. 기존 수주 대형 사업들의 안정적인 이행과 더불어 대외 고객들의 협업 기반이 확대되고 있는 것으로 파악된다. 클라우드&AI 매출은 대내외 AX 프로젝트 및 클라우드 인프라 수주를 통해 YoY 6.7% 성장했다. AI 인프라 및 MSP 사업의 지속적인 확대가 수익성 개선 핵심동력으로 작용하며 영업이익률은 YoY 0.7%p 상승한 7.2%를 기록했다.',
 'pdf_url': 'https://stock.pstatic.net/stock-research/company/16/20260430_company_410118000.pdf',
 'pdf_path': 'naver_company_reports/2026-04-30/2026.04.30_LG씨엔에스_한화투자증권.pdf',
 'detail_url': 'https://finance.naver.com/research/company_read.naver?nid=92285&page=1&searchType=writeDate&writeFromDate=2026-04-30&writeToDate=2026-04-30'}

# 3. NFR 산업분석리포트

In [1]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse, parse_qs
from pathlib import Path
import re
import pandas as pd

BASE_URL = "https://finance.naver.com"
RESEARCH_BASE_URL = "https://finance.naver.com/research/"
LIST_URL = "https://finance.naver.com/research/industry_list.naver"

headers = {
    "User-Agent": "Mozilla/5.0",
    "Referer": "https://finance.naver.com/research/industry_list.naver",
}

target_date = "2026-04-30"

page = 1

params = {
    "keyword": "",
    "brokerCode": "",
    "searchType": "writeDate",
    "writeFromDate": target_date,
    "writeToDate": target_date,
    "upjong": "",
    "x": 48,
    "y": 27,
    "page": page,
}

res = requests.get(
    LIST_URL,
    params=params,
    headers=headers,
    timeout=10,
)

res.raise_for_status()
res.encoding = "euc-kr"

soup = BeautifulSoup(res.text, "html.parser")

print("요청 URL:")
print(res.url)
print("상태 코드:", res.status_code)

요청 URL:
https://finance.naver.com/research/industry_list.naver?keyword=&brokerCode=&searchType=writeDate&writeFromDate=2026-04-30&writeToDate=2026-04-30&upjong=&x=48&y=27&page=1
상태 코드: 200

In [2]:
report_elements = soup.select('a[href*="industry_read.naver"]')
last_page_element = None

for a in soup.select("a[href]"):
    text = a.get_text(" ", strip=True)
    
    if "맨뒤" in text:
        last_page_element = a
        break

print(last_page_element)

if last_page_element is not None:
    href = last_page_element.get("href")
    
    parsed = urlparse(href)
    query = parse_qs(parsed.query)
    
    last_page = int(query["page"][0])
else:
    last_page = 1

print("총페이지 수:", last_page)

None
총페이지 수: 1

In [3]:
total_reports = 0

for page in range(1, last_page + 1):
    params = {
        "keyword": "",
        "brokerCode": "",
        "searchType": "writeDate",
        "writeFromDate": target_date,
        "writeToDate": target_date,
        "upjong": "",
        "x": 48,
        "y": 27,
        "page": page,
    }

    res = requests.get(
        LIST_URL,
        params=params,
        headers=headers,
        timeout=10,
    )

    res.raise_for_status()
    res.encoding = "euc-kr"

    page_soup = BeautifulSoup(res.text, "html.parser")

    page_report_elements = page_soup.select('a[href*="industry_read.naver"]')
    page_report_count = len(page_report_elements)

    total_reports += page_report_count

    print(f"{page}페이지 산업분석리포트 수: {page_report_count}")
    print(res.url)
    print("-" * 80)

print("총페이지 수:", last_page)
print("총산업분석리포트 수:", total_reports)

1페이지 산업분석리포트 수: 9
https://finance.naver.com/research/industry_list.naver?keyword=&brokerCode=&searchType=writeDate&writeFromDate=2026-04-30&writeToDate=2026-04-30&upjong=&x=48&y=27&page=1
--------------------------------------------------------------------------------
총페이지 수: 1
총산업분석리포트 수: 9

In [4]:
first_report_element = report_elements[0]

first_report_title = first_report_element.get_text(" ", strip=True)
first_report_href = first_report_element.get("href")

first_report_url = urljoin(RESEARCH_BASE_URL, first_report_href)

print("첫 번째 산업분석리포트 제목:", first_report_title)
print("첫 번째 산업분석리포트 href:", first_report_href)
print("첫 번째 산업분석리포트 URL:", first_report_url)

첫 번째 산업분석리포트 제목: 바이오텍도 YoY 성장 중, IPO에서 찾는 기회
첫 번째 산업분석리포트 href: industry_read.naver?nid=44388&page=1&searchType=writeDate&writeFromDate=2026-04-30&writeToDate=2026-04-30
첫 번째 산업분석리포트 URL: https://finance.naver.com/research/industry_read.naver?nid=44388&page=1&searchType=writeDate&writeFromDate=2026-04-30&writeToDate=2026-04-30

In [5]:
detail_res = requests.get(
    first_report_url,
    headers=headers,
    timeout=10,
)

detail_res.raise_for_status()
detail_res.encoding = "euc-kr"

detail_soup = BeautifulSoup(detail_res.text, "html.parser")

print("상세 페이지 URL:")
print(detail_res.url)
print("상태 코드:", detail_res.status_code)

상세 페이지 URL:
https://finance.naver.com/research/industry_read.naver?nid=44388&page=1&searchType=writeDate&writeFromDate=2026-04-30&writeToDate=2026-04-30
상태 코드: 200

In [6]:
target_table = detail_soup.select_one('table.type_1[summary="산업분석 리포트 본문내용"]')
save_dir = Path("naver_industry_reports") / target_date
save_dir.mkdir(parents=True, exist_ok=True)

subject_element = target_table.select_one("th.view_sbj")

print(subject_element)

<th class="view_sbj">
<span><em>바이오</em></span>
							바이오텍도 YoY 성장 중, IPO에서 찾는 기회
							<p class="source">하나증권<b class="bar">|</b>2026.04.30<b class="bar">|</b>조회 4691</p>
</th>

In [7]:
industry_name = None
report_title = None
broker = None
report_date = None
views = None

# 업종명
industry_tag = subject_element.select_one("span em")
if industry_tag is not None:
    industry_name = industry_tag.get_text(strip=True)

# 증권사 | 날짜 | 조회수
source_tag = subject_element.select_one("p.source")
if source_tag is not None:
    source_text = source_tag.get_text("|", strip=True)
    source_parts = [x.strip() for x in source_text.split("|") if x.strip()]
    
    print("source_parts:", source_parts)
    
    if len(source_parts) >= 1:
        broker = source_parts[0]
    
    if len(source_parts) >= 2:
        report_date = source_parts[1]
    
    if len(source_parts) >= 3:
        views_text = source_parts[2]
        views_num = re.sub(r"[^0-9]", "", views_text)
        views = int(views_num) if views_num else None

# 리포트 제목
subject_copy = BeautifulSoup(str(subject_element), "html.parser")
subject_copy_element = subject_copy.select_one("th.view_sbj")

for tag in subject_copy_element.select("span, p.source"):
    tag.decompose()

report_title = subject_copy_element.get_text(" ", strip=True)

print("업종명:", industry_name)
print("리포트 제목:", report_title)
print("증권사:", broker)
print("작성일:", report_date)
print("조회수:", views)

source_parts: ['하나증권', '2026.04.30', '조회 4691']
업종명: 바이오
리포트 제목: 바이오텍도 YoY 성장 중, IPO에서 찾는 기회
증권사: 하나증권
작성일: 2026.04.30
조회수: 4691

In [8]:
body_element = target_table.select_one("td.view_cnt")
body_text = None
body_html = None

body_div = body_element.find("div") if body_element is not None else None

if body_div is not None:
    body_text = body_div.get_text("\n", strip=True)
    body_html = str(body_div)

print(body_text)

제약/바이오 섹터는 YoY로 여전히 성장 중, 다만 이벤트 부재가 곧 실적 감소
올해 헬스케어 섹터는 연초대비수익률(YTD) 및 12개월전대비수익률(YoY) 모두 타 섹터 대비 부진한 경향을 보이고 있다. 코스피200헬스케어(이하 “코스피H”)는 YTD로 손실이고, 코스닥150헬스케어(이하 “코스닥H”)도 YTD로는 손실을 겨우 면하는 수준이나, 코스닥H 중시가총액 3,500억원이 초과하면서 의료기기/미용을 제외한 순수 제약사/바이오텍(이하 “코스닥H 선별”)의 가중평균수익률은 YoY로 117.1%이다. 따라서 선별된 기업에 대한 중장기적인 수익률은 여전히 기대할 수 있다 (도표 7, 8 참고). 한편 코스피H와 코스닥H는 모두 미국 제약/바이오 주가와 비슷한 경향성을 띄는데, 대형제약사로 대표되는 코스피H와 비교하여 코스닥H는 나스닥 바이오텍 트렌드(IBB)와 작년 하반기부터 디커플링 되는 현상이 자주 관찰되었다. 이는 작년 하반기부터 기술이전 성과가 둔화되었고, 코스닥H 내 시가총액 상위 종목에서의 악재가 연달아 발생한 것이 원인으로 분석된다. 1.5년 내 IBB와의 트렌드를 보아 바이오텍의 실적이라 할 수 있는 기술이전 이벤트가 발생한다면, 적어도 전고점 수준으로 회복할 수 있을 것이다.

In [9]:
pdf_elements = target_table.select('a[href*=".pdf"]')
pdf_urls = []

for a in pdf_elements:
    href = a.get("href")
    
    if href is None:
        continue
    
    if href not in pdf_urls:
        pdf_urls.append(href)

print(pdf_urls)

pdf_url = pdf_urls[0] if pdf_urls else None

print("선택된 PDF URL:", pdf_url)

['https://stock.pstatic.net/stock-research/industry/57/20260430_industry_28137000.pdf']
선택된 PDF URL: https://stock.pstatic.net/stock-research/industry/57/20260430_industry_28137000.pdf

In [10]:
safe_industry = re.sub(r'[\\/:*?"<>|]', "_", str(industry_name)).strip()
safe_broker = re.sub(r'[\\/:*?"<>|]', "_", str(broker)).strip()

pdf_filename = f"{report_date}_{safe_industry}_{safe_broker}.pdf"
pdf_path = save_dir / pdf_filename

print(pdf_path)

naver_industry_reports/2026-04-30/2026.04.30_바이오_하나증권.pdf

In [11]:
if pdf_url is not None:
    pdf_headers = {
        "User-Agent": "Mozilla/5.0",
        "Referer": first_report_url,
    }

    pdf_res = requests.get(
        pdf_url,
        headers=pdf_headers,
        timeout=30,
    )

    pdf_res.raise_for_status()

    with open(pdf_path, "wb") as f:
        f.write(pdf_res.content)

    print("PDF 저장 완료:")
    print(pdf_path)
    print("파일 크기:", pdf_path.stat().st_size, "bytes")
else:
    print("PDF URL이 없습니다.")

PDF 저장 완료:
naver_industry_reports/2026-04-30/2026.04.30_바이오_하나증권.pdf
파일 크기: 677479 bytes

In [12]:
report_data = {
    "target_date": target_date,
    "industry_name": industry_name,
    "report_title": report_title,
    "broker": broker,
    "report_date": report_date,
    "views": views,
    "body_text": body_text,
    "pdf_url": pdf_url,
    "pdf_path": str(pdf_path) if pdf_url is not None else None,
    "detail_url": first_report_url,
}

report_data

{'target_date': '2026-04-30',
 'industry_name': '바이오',
 'report_title': '바이오텍도 YoY 성장 중, IPO에서 찾는 기회',
 'broker': '하나증권',
 'report_date': '2026.04.30',
 'views': 4691,
 'body_text': '제약/바이오 섹터는 YoY로 여전히 성장 중, 다만 이벤트 부재가 곧 실적 감소\n올해 헬스케어 섹터는 연초대비수익률(YTD) 및 12개월전대비수익률(YoY) 모두 타 섹터 대비 부진한 경향을 보이고 있다. 코스피200헬스케어(이하 “코스피H”)는 YTD로 손실이고, 코스닥150헬스케어(이하 “코스닥H”)도 YTD로는 손실을 겨우 면하는 수준이나, 코스닥H 중시가총액 3,500억원이 초과하면서 의료기기/미용을 제외한 순수 제약사/바이오텍(이하 “코스닥H 선별”)의 가중평균수익률은 YoY로 117.1%이다. 따라서 선별된 기업에 대한 중장기적인 수익률은 여전히 기대할 수 있다 (도표 7, 8 참고). 한편 코스피H와 코스닥H는 모두 미국 제약/바이오 주가와 비슷한 경향성을 띄는데, 대형제약사로 대표되는 코스피H와 비교하여 코스닥H는 나스닥 바이오텍 트렌드(IBB)와 작년 하반기부터 디커플링 되는 현상이 자주 관찰되었다. 이는 작년 하반기부터 기술이전 성과가 둔화되었고, 코스닥H 내 시가총액 상위 종목에서의 악재가 연달아 발생한 것이 원인으로 분석된다. 1.5년 내 IBB와의 트렌드를 보아 바이오텍의 실적이라 할 수 있는 기술이전 이벤트가 발생한다면, 적어도 전고점 수준으로 회복할 수 있을 것이다.',
 'pdf_url': 'https://stock.pstatic.net/stock-research/industry/57/20260430_industry_28137000.pdf',
 'pdf_path': 'naver_industry_reports/2026-04-30/2026.04.30_바이오_하나증권.pdf',
 'detail_url': 'https://finance.naver.com/research/industry_read.naver?nid=44388&page=1&searchType=writeDate&writeFromDate=2026-04-30&writeToDate=2026-04-30'}