# 공시정보

# Step1: corp_code 불러오기

In [2]:
import os
from dotenv import load_dotenv

import requests
import zipfile
import io
import xml.etree.ElementTree as ET
import pandas as pd

load_dotenv()
API_KEY = os.getenv("DART_API_KEY")

url = "https://opendart.fss.or.kr/api/corpCode.xml"
params = {
    "crtfc_key": API_KEY
}

# 1) API 호출
response = requests.get(url, params=params, timeout=30)
response.raise_for_status()

# 2) ZIP 파일을 메모리에서 바로 열기
with zipfile.ZipFile(io.BytesIO(response.content)) as zf:
    xml_filename = zf.namelist()[0]
    with zf.open(xml_filename) as xml_file:
        xml_bytes = xml_file.read()

# 3) XML 파싱
root = ET.fromstring(xml_bytes)

rows = []
for item in root.findall("list"):
    rows.append({
        "corp_code": item.findtext("corp_code"),
        "corp_name": item.findtext("corp_name"),
        "corp_eng_name": item.findtext("corp_eng_name"),
        "stock_code": item.findtext("stock_code"),
        "modify_date": item.findtext("modify_date"),
    })

# 4) DataFrame으로 변환
df = pd.DataFrame(rows)

# 5) stock_code가 결측치가 아니고, 빈 문자열도 아닌 행만 남기기
df = df[df["stock_code"].notna() & (df["stock_code"].str.strip() != "")]
df

,corp_code,corp_name,corp_eng_name,stock_code,modify_date
1944,00260985,한빛네트,"HanbitNet, Inc.",036720,20170630
1956,00264529,엔플렉스,"Nplex,Inc.",040130,20170630
1957,00358545,동서정보기술,"Dong Seo Information Technology Co., Ltd.",055000,20170630
2695,00231567,애드모바일,,032600,20170630
3765,00359614,리더컴,"LEADER COMM.Co.,Ltd",056140,20170630
...,...,...,...,...,...
115726,00683007,엑스큐어,Xcure Corp.,070300,20251215
115760,01182408,소프트캠프,"SOFTCAMP CO., LTD",258790,20251031
115762,00600013,맵스리얼티,MIRAEASSET MAPS REALTY INVESTMENT COMPANY,094800,20251031
115775,00220057,유비케어,"UBCARE CO., LTD.",032620,20251103
115787,00109693,DL,"DL Holdings CO.,LTD",000210,20250919

In [17]:
dup_rows = df[df["corp_name"].duplicated(keep=False)].sort_values("corp_name")
dup_rows

       corp_code corp_name             corp_eng_name stock_code modify_date
95283   00181712        SK                   SK Inc.     034730    20240328
31422   00144155        SK     SK Holdings Co., Ltd.     003600    20170630
23489   00104467      국민은행             Kookmin Bank      031150    20170630
98113   00386937      국민은행              KOOKMIN BANK     060000    20250102
38536   00925453      나무기술       NAMU TECH CO., LTD.     167380    20181211
...          ...       ...                       ...        ...         ...
95538   00159412      한국제지  HANKUK PAPER MFG CO.,LTD     002300    20240628
106276  00793155     핸디소프트           HANDYSOFT, Inc.     220180    20250910
4541    00231521     핸디소프트           HandySoft Corp.     032380    20170630
103392  01453670        휴럼           Hurum Co., Ltd.     353190    20240701
92978   01148909        휴럼           Hurum Co., Ltd.     284420    20240628

[68 rows x 5 columns]

# Step2: 기업개황

In [24]:
url = "https://opendart.fss.or.kr/api/company.json"
params = {
    "crtfc_key": API_KEY,
    "corp_code": "00144155"
}
response = requests.get(url, params=params, timeout=30)
response.json()

{'status': '000',
 'message': '정상',
 'corp_code': '00144155',
 'corp_name': 'SK(주)',
 'corp_name_eng': 'SK Holdings Co., Ltd.',
 'stock_name': 'SK',
 'stock_code': '003600',
 'ceo_nm': '조대식',
 'corp_cls': 'E',
 'jurir_no': '1101110022816',
 'bizr_no': '1168102054',
 'adres': '서울특별시 종로구  종로 26 (서린동)',
 'hm_url': 'www.sk.co.kr',
 'ir_url': '',
 'phn_no': '02-2121-0114',
 'fax_no': '02-2121-1891',
 'induty_code': '64992',
 'est_dt': '19621013',
 'acc_mt': '12'}

# Step3: 공시검색

In [23]:
url = "https://opendart.fss.or.kr/api/list.json"
params = {
    "crtfc_key": API_KEY,
    "corp_code": "00181712",
    "bgn_de": "20100101",
    "end_de": "20251231",
    "page_no": 2,
    "page_count": 100,
    "last_reprt_at": "Y",
}
response = requests.get(url, params=params, timeout=30)
response.json()

{'status': '000',
 'message': '정상',
 'page_no': 2,
 'page_count': 100,
 'total_count': 1943,
 'total_page': 20,
 'list': [{'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '자기주식처분결과보고서',
   'rcept_no': '20250402002980',
   'flr_nm': 'SK',
   'rcept_dt': '20250402',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '지주회사의자회사탈퇴              ',
   'rcept_no': '20250331803084',
   'flr_nm': 'SK',
   'rcept_dt': '20250331',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '타인에대한채무보증결정(자회사의 주요경영사항)              ',
   'rcept_no': '20250328803428',
   'flr_nm': 'SK',
   'rcept_dt': '20250328',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '임원ㆍ주요주주특정증권등소유상황보고서',
   'rcept_no': '20250328001997',
   'flr_nm': '이창민',
   'rcept_dt': '20250328',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '주식등의대량보유상황보고서(일반)',
   'rcept_no': '20250328001930',
   'flr_nm': '최태원',
   'rcept_dt': '20250328',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '타인에대한채무보증결정(자회사의 주요경영사항)              ',
   'rcept_no': '20250327801282',
   'flr_nm': 'SK',
   'rcept_dt': '20250327',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '주요사항보고서(자기주식처분결정)',
   'rcept_no': '20250326001097',
   'flr_nm': 'SK',
   'rcept_dt': '20250326',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '정기주주총회결과              ',
   'rcept_no': '20250326802302',
   'flr_nm': 'SK',
   'rcept_dt': '20250326',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '사외이사의선임ㆍ해임또는중도퇴임에관한신고',
   'rcept_no': '20250326001119',
   'flr_nm': 'SK',
   'rcept_dt': '20250326',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '최대주주등소유주식변동신고서              ',
   'rcept_no': '20250325801333',
   'flr_nm': 'SK',
   'rcept_dt': '20250325',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '투자판단관련주요경영사항(자회사의 주요경영사항)              ',
   'rcept_no': '20250319800866',
   'flr_nm': 'SK',
   'rcept_dt': '20250319',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '사업보고서 (2024.12)',
   'rcept_no': '20250318001364',
   'flr_nm': 'SK',
   'rcept_dt': '20250318',
   'rm': '연'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '의결권대리행사권유참고서류',
   'rcept_no': '20250312000396',
   'flr_nm': '컨두잇',
   'rcept_dt': '20250312',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '감사보고서제출              ',
   'rcept_no': '20250311801943',
   'flr_nm': 'SK',
   'rcept_dt': '20250311',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '감사보고서제출(자회사의 주요경영사항)              ',
   'rcept_no': '20250311801599',
   'flr_nm': 'SK',
   'rcept_dt': '20250311',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '감사보고서제출(자회사의 주요경영사항)              ',
   'rcept_no': '20250311801469',
   'flr_nm': 'SK',
   'rcept_dt': '20250311',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '감사보고서제출(자회사의 주요경영사항)              ',
   'rcept_no': '20250311801390',
   'flr_nm': 'SK',
   'rcept_dt': '20250311',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '감사보고서제출(자회사의 주요경영사항)              ',
   'rcept_no': '20250310800873',
   'flr_nm': 'SK',
   'rcept_dt': '20250310',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '특수관계인에대한출자',
   'rcept_no': '20250307001163',
   'flr_nm': 'SK',
   'rcept_dt': '20250307',
   'rm': '공'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '[기재정정]현금ㆍ현물배당결정              ',
   'rcept_no': '20250307801420',
   'flr_nm': 'SK',
   'rcept_dt': '20250307',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '의결권대리행사권유참고서류',
   'rcept_no': '20250307001140',
   'flr_nm': 'SK',
   'rcept_dt': '20250307',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '주주총회소집공고',
   'rcept_no': '20250307001113',
   'flr_nm': 'SK',
   'rcept_dt': '20250307',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '주주총회소집결의              ',
   'rcept_no': '20250307801310',
   'flr_nm': 'SK',
   'rcept_dt': '20250307',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '증권발행실적보고서',
   'rcept_no': '20250307000968',
   'flr_nm': 'SK',
   'rcept_dt': '20250307',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '특수관계인에대한주식의처분',
   'rcept_no': '20250307000960',
   'flr_nm': 'SK',
   'rcept_dt': '20250307',
   'rm': '공'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '특수관계인에대한증여',
   'rcept_no': '20250307000898',
   'flr_nm': 'SK',
   'rcept_dt': '20250307',
   'rm': '공'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '특수관계인으로부터자산양수',
   'rcept_no': '20250307000862',
   'flr_nm': 'SK',
   'rcept_dt': '20250307',
   'rm': '공'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '현금ㆍ현물배당을위한주주명부폐쇄(기준일)결정              ',
   'rcept_no': '20250307800773',
   'flr_nm': 'SK',
   'rcept_dt': '20250307',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '투자설명서',
   'rcept_no': '20250307000012',
   'flr_nm': 'SK',
   'rcept_dt': '20250307',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '[발행조건확정]증권신고서(채무증권)',
   'rcept_no': '20250306000737',
   'flr_nm': 'SK',
   'rcept_dt': '20250306',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '대규모기업집단현황공시[분기별공시(대표회사용)]',
   'rcept_no': '20250227004499',
   'flr_nm': 'SK',
   'rcept_dt': '20250227',
   'rm': '공'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '[기재정정]현금ㆍ현물배당결정(자회사의 주요경영사항)              ',
   'rcept_no': '20250226800994',
   'flr_nm': 'SK',
   'rcept_dt': '20250226',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '동일인등출자계열회사와의상품ㆍ용역거래변경',
   'rcept_no': '20250213001504',
   'flr_nm': 'SK',
   'rcept_dt': '20250213',
   'rm': '공'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '동일인등출자계열회사와의상품ㆍ용역거래변경',
   'rcept_no': '20250213001481',
   'flr_nm': 'SK',
   'rcept_dt': '20250213',
   'rm': '공'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '지급수단별ㆍ지급기간별지급금액및분쟁조정기구에관한사항',
   'rcept_no': '20250213001463',
   'flr_nm': 'SK',
   'rcept_dt': '20250213',
   'rm': '공'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '매출액또는손익구조30%(대규모법인은15%)이상변경(자회사의 주요경영사항)              ',
   'rcept_no': '20250212800021',
   'flr_nm': 'SK',
   'rcept_dt': '20250212',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '현금ㆍ현물배당결정(자회사의 주요경영사항)              ',
   'rcept_no': '20250212800009',
   'flr_nm': 'SK',
   'rcept_dt': '20250212',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '현금ㆍ현물배당을위한주주명부폐쇄(기준일)결정(자회사의 주요경영사항)              ',
   'rcept_no': '20250212800006',
   'flr_nm': 'SK',
   'rcept_dt': '20250212',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '주식등의대량보유상황보고서(일반)',
   'rcept_no': '20250207000781',
   'flr_nm': '최태원',
   'rcept_dt': '20250207',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '매출액또는손익구조30%(대규모법인은15%)이상변경              ',
   'rcept_no': '20250206801095',
   'flr_nm': 'SK',
   'rcept_dt': '20250206',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '현금ㆍ현물배당을위한주주명부폐쇄(기준일)결정(자회사의 주요경영사항)              ',
   'rcept_no': '20250205801103',
   'flr_nm': 'SK',
   'rcept_dt': '20250205',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '매출액또는손익구조30%(대규모법인은15%)이상변경(자회사의 주요경영사항)              ',
   'rcept_no': '20250205801097',
   'flr_nm': 'SK',
   'rcept_dt': '20250205',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '매출액또는손익구조30%(대규모법인은15%)이상변경(자회사의 주요경영사항)              ',
   'rcept_no': '20250205801094',
   'flr_nm': 'SK',
   'rcept_dt': '20250205',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '매출액또는손익구조30%(대규모법인은15%)이상변경(자회사의 주요경영사항)              ',
   'rcept_no': '20250205800976',
   'flr_nm': 'SK',
   'rcept_dt': '20250205',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '주식등의대량보유상황보고서(약식)',
   'rcept_no': '20250204000392',
   'flr_nm': '국민연금공단',
   'rcept_dt': '20250204',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '지주회사의자회사탈퇴(자회사의 주요경영사항)              ',
   'rcept_no': '20250203801190',
   'flr_nm': 'SK',
   'rcept_dt': '20250203',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '주식등의대량보유상황보고서(일반)',
   'rcept_no': '20250131000504',
   'flr_nm': '최태원',
   'rcept_dt': '20250131',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '[기재정정]금전대여결정(자회사의 주요경영사항)              ',
   'rcept_no': '20250122800353',
   'flr_nm': 'SK',
   'rcept_dt': '20250122',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '[기재정정]금전대여결정(자회사의 주요경영사항)              ',
   'rcept_no': '20250122800346',
   'flr_nm': 'SK',
   'rcept_dt': '20250122',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '감자결정(종속회사의주요경영사항)              ',
   'rcept_no': '20250115800508',
   'flr_nm': 'SK',
   'rcept_dt': '20250115',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '임원ㆍ주요주주특정증권등소유상황보고서',
   'rcept_no': '20250108000343',
   'flr_nm': '이현준',
   'rcept_dt': '20250108',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '임원ㆍ주요주주특정증권등소유상황보고서',
   'rcept_no': '20250108000338',
   'flr_nm': '김민환',
   'rcept_dt': '20250108',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '임원ㆍ주요주주특정증권등소유상황보고서',
   'rcept_no': '20250108000333',
   'flr_nm': '고재웅',
   'rcept_dt': '20250108',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '임원ㆍ주요주주특정증권등소유상황보고서',
   'rcept_no': '20250108000312',
   'flr_nm': '유정준',
   'rcept_dt': '20250108',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '최대주주등소유주식변동신고서              ',
   'rcept_no': '20250108800472',
   'flr_nm': 'SK',
   'rcept_dt': '20250108',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '지주회사의자회사탈퇴              ',
   'rcept_no': '20250103800664',
   'flr_nm': 'SK',
   'rcept_dt': '20250103',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '최대주주등소유주식변동신고서              ',
   'rcept_no': '20241226800727',
   'flr_nm': 'SK',
   'rcept_dt': '20241226',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '[기재정정]생산중단(자회사의 주요경영사항)              ',
   'rcept_no': '20241226800512',
   'flr_nm': 'SK',
   'rcept_dt': '20241226',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '해외증권거래소등에신고한주요공시사항의국내신고(자회사의 주요경영사항)              ',
   'rcept_no': '20241224800079',
   'flr_nm': 'SK',
   'rcept_dt': '20241224',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '타법인주식및출자증권처분결정              ',
   'rcept_no': '20241223800749',
   'flr_nm': 'SK',
   'rcept_dt': '20241223',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '해외증권거래소등에신고한주요공시사항의국내신고(자회사의 주요경영사항)              ',
   'rcept_no': '20241223800727',
   'flr_nm': 'SK',
   'rcept_dt': '20241223',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '감자결정(종속회사의주요경영사항)              ',
   'rcept_no': '20241218800613',
   'flr_nm': 'SK',
   'rcept_dt': '20241218',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '투자판단관련주요경영사항(자회사의 주요경영사항)              ',
   'rcept_no': '20241217800382',
   'flr_nm': 'SK',
   'rcept_dt': '20241217',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '타인에대한채무보증결정(자회사의 주요경영사항)              ',
   'rcept_no': '20241216801838',
   'flr_nm': 'SK',
   'rcept_dt': '20241216',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '타인에대한채무보증결정(자회사의 주요경영사항)              ',
   'rcept_no': '20241216801831',
   'flr_nm': 'SK',
   'rcept_dt': '20241216',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '공정거래자율준수프로그램운영현황(안내공시)              ',
   'rcept_no': '20241213800079',
   'flr_nm': 'SK',
   'rcept_dt': '20241213',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '특수관계인으로부터부동산임차',
   'rcept_no': '20241211000335',
   'flr_nm': 'SK',
   'rcept_dt': '20241211',
   'rm': '공'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '동일인등출자계열회사와의상품ㆍ용역거래',
   'rcept_no': '20241211000326',
   'flr_nm': 'SK',
   'rcept_dt': '20241211',
   'rm': '공'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '동일인등출자계열회사와의상품ㆍ용역거래',
   'rcept_no': '20241211000320',
   'flr_nm': 'SK',
   'rcept_dt': '20241211',
   'rm': '공'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '동일인등출자계열회사와의상품ㆍ용역거래',
   'rcept_no': '20241211000314',
   'flr_nm': 'SK',
   'rcept_dt': '20241211',
   'rm': '공'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '주식등의대량보유상황보고서(일반)',
   'rcept_no': '20241206000544',
   'flr_nm': '최태원',
   'rcept_dt': '20241206',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '투자판단관련주요경영사항(자회사의 주요경영사항)              ',
   'rcept_no': '20241205800261',
   'flr_nm': 'SK',
   'rcept_dt': '20241205',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '증권발행실적보고서',
   'rcept_no': '20241128001028',
   'flr_nm': 'SK',
   'rcept_dt': '20241128',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '대규모기업집단현황공시[분기별공시(대표회사용)]',
   'rcept_no': '20241128000768',
   'flr_nm': 'SK',
   'rcept_dt': '20241128',
   'rm': '공'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '투자설명서',
   'rcept_no': '20241128000025',
   'flr_nm': 'SK',
   'rcept_dt': '20241128',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '[발행조건확정]증권신고서(채무증권)',
   'rcept_no': '20241127000853',
   'flr_nm': 'SK',
   'rcept_dt': '20241127',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '투자판단관련주요경영사항(자회사의 주요경영사항)              ',
   'rcept_no': '20241127800618',
   'flr_nm': 'SK',
   'rcept_dt': '20241127',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '분기보고서 (2024.09)',
   'rcept_no': '20241114002693',
   'flr_nm': 'SK',
   'rcept_dt': '20241114',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '동일인등출자계열회사와의상품ㆍ용역거래',
   'rcept_no': '20241114001478',
   'flr_nm': 'SK',
   'rcept_dt': '20241114',
   'rm': '공'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '동일인등출자계열회사와의상품ㆍ용역거래',
   'rcept_no': '20241114001465',
   'flr_nm': 'SK',
   'rcept_dt': '20241114',
   'rm': '공'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '[기재정정]타법인주식및출자증권취득결정(자회사의 주요경영사항)              ',
   'rcept_no': '20241114800620',
   'flr_nm': 'SK',
   'rcept_dt': '20241114',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '임원ㆍ주요주주특정증권등소유상황보고서',
   'rcept_no': '20241107000323',
   'flr_nm': '조현철',
   'rcept_dt': '20241107',
   'rm': ''},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',
   'report_nm': '유상증자결정(자회사의 주요경영사항)              ',
   'rcept_no': '20241107800449',
   'flr_nm': 'SK',
   'rcept_dt': '20241107',
   'rm': '유'},
  {'corp_code': '00181712',
   'corp_name': 'SK',
   'stock_code': '034730',
   'corp_cls': 'Y',

# Step4: 공시서류원본파일

In [16]:
import requests

url = "https://opendart.fss.or.kr/api/document.xml"
params = {
    "crtfc_key": API_KEY,
    "rcept_no": "20251231800604"
}

res = requests.get(url, params=params, timeout=30)
res.content

# with open("dart_original.zip", "wb") as f:
#     f.write(res.content)

b'PK\x03\x04\x14\x00\x08\x00\x08\x008\xbc\x1b\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00\x0020251231800604.xml\xed[[o\x1b\xc7\x15~/\xd0\xff0\xa0\x11X6x\xd9\x0bE\x8a7\x01q\x9c\x02E\xdc\x97\xda\x05\xd2\'aE\xae\xc4\xadW$K\xaee\xb9F\x00\xda\xa6\x005ba\t5#J&\r\xa6V`\xd9P\x00F\xa2\x1d\x19U\xfeL\xfb\xc6\x1d\xfe\x87\x9e\x99\xd9]rE./2EJm-_\xf623\xe7\x9c\xef|s\xce\xcc\x99u4\xa9\xad\xa8\xf3\xbf\xfe\x15\x8a&e)1\x8f\xe0\nEWdMB\xf1tJ\x93SZ\xcc\xb5\x9cP\\(\xa9i\x19\x8f\xfc\xe7\x07\xcaj\xcc\xf5\xb5\xe7\x0f\x9f{\xee\xc9k\xda\x1d\xe9Q\xfa\x81\xf6;Y\xcb*\xf1\x9c\xabgg\r\x9a\xf9\x88\x8c\x08\x8a\'\xa5lN\xd6b\xf2\x83\xb8\xe7~\xd6>\xe4\x17\xac\xbd\xe7\xde\xa3\x8cl\x0et\xf7\xde\x1f\xef|\t\xaay\xd7\x96\xd2\xd9\x95\x1c\xba\x89\x1e\xa3%h\xe7Y\x92V\x14\xf5Q\x18\xe9\xcf7\xf1\xcb<>jD\xbe\xb1Z-h\x8a\xa6\xca\xed\xb69\xe5/r\x18\xf1bF\x8b\xa0\x8c\x94H(\xa9e\x14F\x1c\xfc\xf0\xf0\x17\xe9\xd8\x16\xa0I\x8b\xd0\xf51\x11\x8el\xbd\xb9\xccZ\x84=5\x86\x08\xb7\x9f,\xa6\xb3\t9\xeb\x89\xa7UU\xca\xe4\xe4\xb0ya\xbc\x86\xdbt6\x8c\xae\x89\xb7\xc9\x0f<\xfc\xa6C^\xc2\x14f\x0c\xebQ\xe5%-\xdc%\xcd\xa3\xa53\xc3KT\x95\x94\xecI\xca\xcarR\x0b\x0b\x82\xd5\xabK\x11\xf2\xd0w\x93\xf8\xc7#\xa9\xcar*\x9c%]"7}\xec\xd5\xaa\x9c\xd5\x94\xb8\xa4\x1a/W\x94DB\x95m\x1a\x000\x995\x94K\xabJ\x02]\x0b.\x91\x1ff_\xdb\xc2\\FJ\x996\xfan&\x94\\F\x95\xc0qJ\x8a*\xb9\xa8\xa6\xe3\xf7-\x816\x0c\xc4.\x0c\xa8vTd\x7f;{cf>]LkZz\xa5\xe3E\x87\xfdDpdx\xe3\xb9\xb6\xf1\xb7o\x91\x9f3\xc6{\x95\x95\xe5\xc7\x9d]\x10\xeds\x16")\x0c\x86\xdc\' \xd9\xfd\xc4\x87\xfcs\x81@\xa7\x96\t9\x9e\xceJ\x9a\x92N\x85Q*\x9d\x92\xedd\x92\xc2R\\SV\xe5q\x8c\xb4\xaa\xe4\x14M\xb6\xd89\xea@\xed\xa1>\x0f\'\xd3\x80\xa5} \x8e\x9b\xbb\xf5\xa58\xc20\x0bJ*\xf3@{<\x18\xfe\xf3\xd0\xe8\x02\x18\x04\xbaG},z\xb1HFc\xd2\xfc\xdd\xaf|x\xb3\xd6\xfc\xb9\x827+\xb8\xb0\xdf\xda8\xc4\xaf\xb6\xf4\xbf\xff\xe4\x9b\x118a\xd6\xcb\x0b^\x91\xbf\xd1\xb3E\xd4\xc7F \xa3E}V\xa0\x8e.\xa6\x13\x8f\x0c\x11\te\x15\xc5U)\x97\x8b\xb9\x18hF\x14\xa5o\x8cK\xd6JI\xc4\\w~{k\xe1\xce\x17\x1c\xc7\xb9PN{\xa4\xca1\xd7C%\xa1%\xc3\x01\x8e\xd8\xd5\x0e}\x10\xf9\xb4H\xc4\nz\x105\x05\xf8\xcb\x1c\xda>\xf8\xd9;\x14\xa5\xb3\x7f\xf0\xf8\xf4\xf6!s\xc3bZMD:\x10\x8dCR\x90\xb3\x11\xd7<\xae\x95\xc8o@\xe7\xb86\xa3\x1f7\xe0\x9f\x1bQ\x1f\x91\xd0)\x91EpF\x91\x98\x0b\xacc\x97\x94w\t){\x1f\xf4H\x02\xb3m\xcfU"8\xe6\xba\x16\xa0\xbf\\(.\xab\xaaaq\xcc\xc5\xb3{\x90\x13\xa7\xf70$\xc1\xef\xeb\xdf\x00\xc4\xb7\xe7\x16\xc8?\xdc\xc2="\x95\xb7\xa0\\\x91\xb2\xcbJ\x8a0\x84\x92T0."} pu\x18\x01V\xb4\xfdj=\xca\xda\xee\xe1A\x02\xd1\xf1b.\xbf\xe8\x87\xee=\xc0\x86\x17\xdd\x92\xba\xe2\xbd\x05m\xf5\x14\xc8fB\n\x8cK8J\xe4\x01&S\xa2\x8dsl\xa2\x9e\xe1\x14\xb4\xeee0\xe1\xbc\x87\x17<"\xe7(\x13\x1e\xd8\xcc\x86\xfb3\xc8\xc0\x13\x82\xbd3\x05\xf8\tQ\xe0\xf7rF\x964J\x04\xeeS\x88`D\xb7\xee\xc4\xfa)\x0c\x118\xae7C\x84\xde\\\xe4\xbd\x88q\xa2\xd9\xc8\xeb\xb5\x03\xd4<~O\x03RE\xff\xa1\xdc\x9f \x80&y\r"]\x16=;\x84\x0f&\x8b\xbf\xb7F,*\xa2\xce\xb0\x88h\\\x1c\x929c\x85G\xe8\x03\x0f\xaeU\xf0\x87\n\xcc\xa5\xe9\xe0\x04\x93J$\x93J\xe0\xa6\x03\x8dhB\x83\x9f\x1e\xe2Jm: 0~4O6p\xe9{\xa4\xd7\x9f\xa3\xe6I\xbdY/\x18\x9a}"0\x96\xd2\xa2\xa5t\xc0\t$\x87P\xef\xef\x00\xa9U\xfaq\x1a\x9er\xce\xb0\xa0\x90\xfe\xee\xedPi`\\"q\xad0Qy\xad\x97\x85\xf1c>\x98\xad\xce\xd1\xc4X\xe7=m\xe0\x9d\x1f\x91\x07u\xf2w\x06\xbf\xdc\xba12:\xe7V\x86w\x07gE7\xcc+7\xc7\xfeLNtH\x0c\xb8\xc5\xb9\x90;\xe8\x0f\xb9\xb9\xb9\xe0\xa5\xf6\x10uO\x9d<9>\xd1\x8by\xfdca\xe6\xb3\tzI\x08yg\xfd\x13$\xc5\xac7x\x99\xfc!z\xad)B\xe3:\xf8\xe3\x1f\xeb\xfa\xeb\xe2\xc0\xac;V\x1f\x98\xcbW~\xa22\x03\x03dN\xde\x1bA/\xc9\xaf\xadgy\xc3)\xad\xe2\x96\xbey\xd0<>Ely\xd4*\xc1\xbam\x7f\x1b\xef\xbd\x18\x90\xee\xc6\xcf[\xc8\xb3\xcf\x9e\x80r\xe8:Y\xb2u\xccY\x1aU\xaf\xe3j\x1e\xe1\xf7\x95\xe6\xcf\xa7\x88,Wv\xd6\xf1N]\x7f^@\xfa\x9b-\x04\x97\xcd#h}\xa8\x1f6`M\xd7\xda\xae\x10+\xf1~\x1e\xbf*xa\xe3\x9dE\x7f\x92V\xa5\x98\x8b\xd40\xc3>\xdf\xda\x8a\xea\x95`\x83\x90\x94\xbd\xe9\xec\xb2oMR\xa5\x94\x8f\xb4 V\x8c\xd0Xh\xabLV\t\xb0\xaa|\xb5\r\xb4f\xaaV\x1b\x04\xc1\xbd""\x9aU\xcbd\xc3Vm\xe8o\xebn\xd6\xd8\x9c\x03\xb4\xb1\xb1Fn\x1e\x17Z{\x7f\x83!\x8d\xd7\x08\x977\xd8^O\xff\x9e\xacXQ\xeb\xbb\x1f \x1d\xc2\x88\xbf\xe0\xf2\x93\xd6n\x19.\xe8\x92\xc9\xe8\x8f\xdf\x14Z\xdf\xfd\x15\x9cI:\xedl\x91\x1e\xfaq\x1e\x1a\xe9[5\x847\xca\x80\xea\x06\xae\x16\xbd\x97\xcb\xa90O\x04}\xbd0}_\xb6J\r}\xf3\xa3\x99=\xbe}q\x06\xe7\xe3|k\xf7\x05\xc0\x8a\xf4\x17u\xbdzj\xa0\rN\x85W\r\xd8L\xe8[\x15bl\xebY\xc5rt\xd7\xda\x80Q\x83mG\xd8>\x04\x06j\x95\x0b`n\xf3c\x11\xbf\xc9\x03S\xda\xde\xdc\x86\xf1\x11\xebM\x8d\xbf\xde\x19H\x19q\xca\xdb\xa4\x07\xde-\x10\xba\x10n\xd8\xa9\x04\xca\xb5v\x894}\xablZ\xb4WGD\x1c\x15o2\x0cF\xffo\xd8\xd7\x8f\xb4\xa3\x9f\r\x85&\xb4\xa3\x07I#L\xa5\x9ez\xb9\xe6=\xe3tP\xd4\xd7Y\xfc\xb3\xdd\xd9o\xba\n\x95\xec\xc4\xc6\xb1\xa6\xd8\xbd\xdc\x9f\r\xcd\x99\xe6\x0c\xac\x1a\xf6\xaf\x1b\x0c\xa7m\xbb`\xcas\xfc\x85\x16L\'\xcbq\xe1<\x1c\x9f\\\xd5\x8aw\xaak\xf2\xbd\xea\x9a\xe0kX{\xec\x15I&\xaf\x9e\x0cW\xc6\x0c\xf9G)c\x86zJ\xbd\xfb\x15\x89\xcd\xeb\'\xfaQ\x8d$\xe8\xf5\xf2\x0c~}:\xe4^ (8\xecg\x83BO\x03I\\~}\n+)\x96F\xd8z\x8a\x95\xc4\xafr\xac\xfd?\x0f\xc7\xc0C\xb2:\xfbv\x1f\x9f\xe6\t\x0b\xcb\x07\xff\xde\xa8\\i\x0e\x0e\x9dN&KU\xfe|T\xe5\xcfE\xd5\xb3<\xb5\x93\xd4\xa1\x82*\x04\x82\x0e\x0e\r\x04\x1d\xd6\xd3\xc6\x1a\xf0\xfd\xa1\xfe\xc1\xa90\xe6 L\x14Ga\xae\xe80_\xbaN<{+ag\xd1\x85\x80a\xd6\xde\xf4b\x1e\xd6\xddS\xc0\x02\xb2I\xf9\x00\xc16\x0b?\xad\x0b\xfa\xf3]\xba\x17c\xb7"\xdc\x9e\x0f\x98l\xfa!S\xd6o)\xcb\xcf:\x94R\xe1\xc5\x10%\xb0>\xc8\x98\x02x\x07\xe4\xe1\xc5p\xb5\xdaa\xab\xa0\x17\xe7\x8e\x1eG\xa5C\x15)\x07\xf9cl\x10u\xed~/\x03D\xb3n\x02\x12\'\xce\xb9\x83B\xc0-\x84\xc4K\x04\xd2\xa0Z\xedD\x81\xeaSV\x9d\x188\x00\x08\xc4^\xfd\xdd\x81~T\x82\xe5\n\xde\x81\x1c\x90\x9fB\xdcc\x85\x92\xa9\xc5}\xab\xa2\xac\xbf{\x8bkO\xa6\x96\x04II\rVW\x88\xe4\x9f\xea6\xae\x16\x10\xae\x14h\x01\x95fG\xf4)\xe9\xd1\xca\x02\xc2\xb9\xb3\x80\xdf^x\x9fD\x16\xb0J\xa0S\xf0\x89y\x98\xce\x87\xa6\x1d\xc2\x06\x1co\\0\x08}\xcf\x1c&0;g\xbd\xed\xda\xb7U\xfa\x9e!W\xb4\x92}\xe3\nRc\x0c\x93\xd1C\x0f-vO\x184\x08\xd7Op\xa1:0\x80\x8f\x8f\x93T\xde\x8c\xfen\xfdR$S\xcf\xb4\x13\xe9\x87\r@\xe4\xaa\xc31\x96-T\xb3\xbe\x05\x84\x9c\xe9dg\xb3\x9eG\xb8T\xd07\x8b\xc6[Hkd\xbd:,k/,\xebR\xf1S\x9b\xc2\x01\xaf\xf9\xedX\xa5\xa6\x1f7\x8c\x03S\xb2\xc5\xda{;\x919L\xc5\xf6\xfdT\xeb"\xd1\x9f\xf6\x9ce\xe6\x93\xc3\xebR\xe5\xea\x98\xdf\xa9N\x0f\x0e\x8e:_\xc7t|\x7f\x91@]\xc8\x91\xef\xda\x8a\x9a\xca\x85G:\xf8\x1d\xad\xcb\xff\xfc\xf1\xefd`\x86\xad\x1b\x10\xa1\xf9S\xa3MY\x8a[\xe1\x04R\n\xec\xe5`W\x8b\x8c"5\xd8\xc5\x16\x8d\xec\xa3\xd0\xf7\x87\xf8\xa8a\xb6\xd8\xdc\'\xd0\x83/`\x08J\xf9\xea)yK\xba|(\xc2\x03\x82\r\xec\xca\x80H\xc6zK/S\x8fv>\xa3Y\x0e\x10\'\x1fQRp\x007\x18\xb2yT$\xdb8\x80\xa4U:\x98\x10*\xe4{\x10\xfb\x81\x00=\x96\xa2J\x81\x86\xafO\xad\x13\n\xd4\xfb\x00\xab]\xe7G\xd6y\x06\xfbd\xc4\xdd\xeb\x9b\x192\xe7\x8c\tV!\x9f\x96\xf4\x94N\xc7\x04H\x9e\xd6q\xa3J\xbf\xcd\xfdX \xa1\x05\xa0\xed\xa3D\xe9\x17$\xf2\xde\xc0g\xce_\x14\x0c\x990B\x0e\xc99\xd437\xff+\xffO\x83N\x8c\xd8\x83\xf3\xb1\xe0\x1f%\xd6A\xeb\xf3&\x853\xc7\'\xf6\xb3\x93\x8e\xd3\x11\xe3\x92\\G}\xb4\x07\xf9\x7fI\xf4\xff{\xfe\x07PK\x07\x08\xcc\x9b\x94\x8ac\t\x00\x00\xf69\x00\x00PK\x01\x02\x14\x00\x14\x00\x08\x00\x08\x008\xbc\x1b\x00\xcc\x9b\x94\x8ac\t\x00\x00\xf69\x00\x00\x12\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0020251231800604.xmlPK\x05\x06\x00\x00\x00\x00\x01\x00\x01\x00@\x00\x00\x00\xa3\t\x00\x00\x00\x00'

# 정기보고서 주요정보

# Step1: 증자(감자) 현황

In [21]:
import requests

url = "https://opendart.fss.or.kr/api/irdsSttus.json"
params = {
    "crtfc_key": API_KEY,
    "corp_code": "00181712",
    "bsns_year": "2024",
    "reprt_code": "11011"
}

res = requests.get(url, params=params, timeout=30)
res.json()

{'status': '000',
 'message': '정상',
 'list': [{'rcept_no': '20250318001364',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'isu_dcrs_de': '-',
   'isu_dcrs_stle': '-',
   'isu_dcrs_stock_knd': '-',
   'isu_dcrs_qy': '-',
   'isu_dcrs_mstvdv_fval_amount': '-',
   'isu_dcrs_mstvdv_amount': '-',
   'stlm_dt': '2024-12-31'}]}

# Step2: 배당에 관한 사항

In [25]:
import requests

url = "https://opendart.fss.or.kr/api/alotMatter.json"
params = {
    "crtfc_key": API_KEY,
    "corp_code": "00181712",
    "bsns_year": "2023",
    "reprt_code": "11011"
}

res = requests.get(url, params=params, timeout=30)
res.json()

{'status': '000',
 'message': '정상',
 'list': [{'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '주당액면가액(원)',
   'thstrm': '200',
   'frmtrm': '200',
   'lwfr': '200',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '(연결)당기순이익(백만원)',
   'thstrm': '-776,798',
   'frmtrm': '1,098,683',
   'lwfr': '1,965,612',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '(별도)당기순이익(백만원)',
   'thstrm': '362,974',
   'frmtrm': '544,415',
   'lwfr': '1,499,764',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '(연결)주당순이익(원)',
   'thstrm': '-13,941',
   'frmtrm': '19,432',
   'lwfr': '37,010',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '현금배당금총액(백만원)',
   'thstrm': '276,469',
   'frmtrm': '280,149',
   'lwfr': '447,594',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '주식배당금총액(백만원)',
   'thstrm': '-',
   'frmtrm': '-',
   'lwfr': '-',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '(연결)현금배당성향(%)',
   'thstrm': '-',
   'frmtrm': '25.50',
   'lwfr': '22.80',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '현금배당수익률(%)',
   'stock_knd': '보통주',
   'thstrm': '2.60',
   'frmtrm': '2.50',
   'lwfr': '3.10',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '현금배당수익률(%)',
   'stock_knd': '우선주',
   'thstrm': '3.40',
   'frmtrm': '2.90',
   'lwfr': '3.60',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '주식배당수익률(%)',
   'stock_knd': '보통주',
   'thstrm': '-',
   'frmtrm': '-',
   'lwfr': '-',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '주식배당수익률(%)',
   'stock_knd': '우선주',
   'thstrm': '-',
   'frmtrm': '-',
   'lwfr': '-',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '주당 현금배당금(원)',
   'stock_knd': '보통주',
   'thstrm': '5,000',
   'frmtrm': '5,000',
   'lwfr': '8,000',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '주당 현금배당금(원)',
   'stock_knd': '우선주',
   'thstrm': '5,050',
   'frmtrm': '5,050',
   'lwfr': '8,050',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '주당 주식배당(주)',
   'stock_knd': '보통주',
   'thstrm': '-',
   'frmtrm': '-',
   'lwfr': '-',
   'stlm_dt': '2023-12-31'},
  {'rcept_no': '20240319000757',
   'corp_cls': 'Y',
   'corp_code': '00181712',
   'corp_name': 'SK',
   'se': '주당 주식배당(주)',
   'stock_knd': '우선주',
   'thstrm': '-',
   'frmtrm': '-',
   'lwfr': '-',
   'stlm_dt': '2023-12-31'}]}

# 주요사항보고서 주요정보

In [32]:
import requests

url = "https://opendart.fss.or.kr/api/mgRs.json"
params = {
    "crtfc_key": API_KEY,
    "corp_code": "00181712",
    "bgn_de": "20150101",
    "end_de": "20231231"
}

res = requests.get(url, params=params, timeout=30)
res.json()

{'status': '000',
 'message': '정상',
 'group': [{'title': '일반사항',
   'list': [{'rcept_no': '20150608000268',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'rpt_rcpn': '20150528000671',
     'stn': '흡수합병',
     'bddd': '2015년 04월 20일',
     'ctrd': '2015년 04월 20일',
     'gmtsck_shddstd': '2015년 05월 06일',
     'ap_gmtsck': '2015년 06월 26일',
     'aprskh_pd_bgd': '2015년 06월 26일',
     'aprskh_pd_edd': '2015년 07월 16일',
     'aprskh_prc': '에스케이씨앤씨 주식회사 기명식 보통주식: 230,940원\nSK주식회사 기명식 보통주식: 171,853원\nSK주식회사 기명식 우선주식: 114,536원',
     'mgdt_etc': '2015년 04월 21일\n2015년 06월 11일\n2015년 06월 27일\n2015년 06월 27일∼2015년 07월 27일\n2015년 06월 27일∼2015년 07월 31일\n2015년 08월 01일\n\n2015년 08월 03일\n\n2015년 08월 03일\n2015년 08월 03일\n2015년 08월 14일\n2015년 08월 17일',
     'rt_vl': '에스케이씨앤씨 주식회사 기명식 보통주 : SK주식회사 기명식 보통주 = 1 : 0.7367839\n에스케이씨앤씨 주식회사 기명식 우선주 : SK주식회사 기명식 우선주 =1 : 1.1102438',
     'exevl_int': "(1) 보통주 : 해당사항 없음\n\n(보통주의 경우 합병 당사 회사인 에스케이씨앤씨 주식회사와 SK주식회사 모두 유가증권시장주권상장법인이므로 '자본시장과금융투자업에관한법률' 시행령 제176조의5 제1항제1호에 의거하여 합병가액을 산정한 후, 이를 기초로 합병비율을 산정) \n\n(2) 우선주\n\n- 에스케이씨앤씨 주식회사 우선주 : 삼일회계법인\n- SK주식회사 우선주 : 유가증권시장에 ",
     'grtmn_etc': '합병주식의 교부와 단주 매각 대금 지급 외에는 별도의 합병 교부금 지급은 없습니다.'},
    {'rcept_no': '20210901000431',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'rpt_rcpn': '20210820000406',
     'stn': '흡수합병',
     'bddd': '2021년 08월 20일',
     'ctrd': '2021년 08월 23일',
     'gmtsck_shddstd': '2021년 09월 06일',
     'ap_gmtsck': '2021년 10월 29일',
     'aprskh_pd_bgd': '-',
     'aprskh_pd_edd': '-',
     'aprskh_prc': '-',
     'mgdt_etc': '2021년 08월 20일\n2021년 09월 06일\n2021년 09월 06일 ~ 2021년 09월 23일\n2021년 10월 29일\n2021년 10월 29일 ~ 2021년 11월 30일\n2021년 11월 30일\n2021년 12월 01일\n2021년 12월 01일\n2021년 12월 01일\n2021년 12월 07일\n2021년 12월 27일',
     'rt_vl': '1: 1.5778412\n(SK 주식회사 보통주 : SK머티리얼즈 주식회사 보통주)',
     'exevl_int': '해당사항 없음',
     'grtmn_etc': '합병 주식의 교부와 단주 매각 지급 외에는 별도의 합병 교부금 지급은 없습니다.'}]},
  {'title': '발행증권',
   'list': [{'rcept_no': '20150608000268',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'fv': '200',
     'slprc': '235,073',
     'slta': '6,196,602,794,382',
     'kndn': '기명식보통주',
     'cnt': '26,360,334'},
    {'rcept_no': '20210901000431',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'fv': '200',
     'slprc': '264,076',
     'slta': '1,574,653,234,804',
     'kndn': '기명식보통주',
     'cnt': '5,962,879'},
    {'rcept_no': '20150608000268',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'fv': '200',
     'slprc': '106,328',
     'slta': '60,196,002,280',
     'kndn': '기명식우선주',
     'cnt': '566,135'}]},
  {'title': '당사회사에관한사항',
   'list': [{'rcept_no': '20150608000268',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'cmpnm': '에스케이씨앤씨 주식회사',
     'sen': '존속회사',
     'tast': '5,307,039,000,000',
     'cpt': '10,000,000,000',
     'isstk_knd': '보통주',
     'isstk_cnt': '44,000,000'},
    {'rcept_no': '20210901000431',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'cmpnm': 'SK 주식회사',
     'sen': '존속회사',
     'tast': '25,306,014,000,000',
     'cpt': '15,385,000,000',
     'isstk_knd': '보통주',
     'isstk_cnt': '70,360,297'},
    {'rcept_no': '20150608000268',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'cmpnm': '에스케이씨앤씨 주식회사',
     'sen': '존속회사',
     'tast': '5,307,039,000,000',
     'cpt': '10,000,000,000',
     'isstk_knd': '우선주',
     'isstk_cnt': '-'},
    {'rcept_no': '20210901000431',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'cmpnm': 'SK 주식회사',
     'sen': '존속회사',
     'tast': '25,306,014,000,000',
     'cpt': '15,385,000,000',
     'isstk_knd': '우선주',
     'isstk_cnt': '566,135'},
    {'rcept_no': '20210901000431',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'cmpnm': 'SK머티리얼즈 주식회사',
     'sen': '소멸회사',
     'tast': '1,232,738,000,000',
     'cpt': '5,274,000,000',
     'isstk_knd': '보통주',
     'isstk_cnt': '10,547,673'},
    {'rcept_no': '20150608000268',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'cmpnm': 'SK주식회사',
     'sen': '소멸회사',
     'tast': '92,997,730,000,000',
     'cpt': '238,609,000,000',
     'isstk_knd': '보통주',
     'isstk_cnt': '46,961,812'},
    {'rcept_no': '20210901000431',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'cmpnm': 'SK머티리얼즈 주식회사',
     'sen': '소멸회사',
     'tast': '1,232,738,000,000',
     'cpt': '5,274,000,000',
     'isstk_knd': '우선주',
     'isstk_cnt': '-'},
    {'rcept_no': '20150608000268',
     'corp_cls': 'Y',
     'corp_code': '00181712',
     'corp_name': 'SK',
     'cmpnm': 'SK주식회사',
     'sen': '소멸회사',
     'tast': '92,997,730,000,000',
     'cpt': '238,609,000,000',
     'isstk_knd': '우선주',
     'isstk_cnt': '509,920'}]}]}